meta_product_name: "Lyltalent"
meta_title: "Lyltalent - Musicien"
meta_description: "Lyltalent est une plateforme de mise en relation entre musiciens et organisateurs d'événements,
  facilitant la découverte et l'embauche de jeunes talents : groupes, musicien soliste, rappeurs et DJ.
  Lyltalent soutient l'organisation d'événements culturels et musicaux en France, en mettant en relation les organisateurs
  avec les bons artistes."
meta_image: "Lyltalent_x1200.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
